### ISSUE TITLE
ReturnURL未收到回傳結果

### ISSUE THREAD

**Issue by LuLue7775** [ECPay/ECPayAIO_Node.js#10]
你好，
情況是server端ReturnURL未收到結果，但前端OrderResultURL有收到成功結果，
有用https，均在dev mode和prod mode都測試過，

ReturnURL有用postman測過是可收發訊息的，
請問還有哪些情況可能造成server端收不到結果？

**Comment by AllennChang** [comment]
您好, 感謝你的發問, 因為協助查詢Log 看是否有傳送,ReturnUrl , 請幫忙寫信到 techsupport@ecpay.com.tw
提供您的MID 特店編號及訂單編號, 我們會有專員協助查詢及回覆您查詢結果,

**Comment by LuLue7775** [comment]
您好，
目前是用測試id，這樣是不是就無法查詢log?

**Comment by AllennChang** [comment]
可以, 測試id也可以查詢

**Comment by LuLue7775** [comment]
感謝，找到問題了
status 308
傳過去的returnURL最後面要加/
