### ISSUE TITLE
chk_mac 始終對不上

### ISSUE THREAD

**Issue by LuLue7775** [ECPay/ECPayAIO_Node.js#11]
你好，
根據 payment_client.helper.valid_chkmc_string() 去驗證前端接收到的字串，但驗證不成功
其中的動作大概是把前端接收到的字串轉為物件，再去掉CheckMacValue，用gen_chk_mac_value重算一次
但始終對不上，
請問有可能有甚麼地方出錯了？

**Comment by AllennChang** [comment]
您好, 感謝您的發問, 
因為要檢核失敗問題, 需要請您幫忙寫信到我們客戶專員信箱techsupport@ecpay.com.tw , 
並提供您串接用的MID及交易編號, 
由客服專員協助查詢後回覆您
