### ISSUE TITLE
Invalid 'main' field

### ISSUE THREAD

**Issue by karocksjoelee** [ECPay/ECPayAIO_Node.js#13]
`[0] (node:10166) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/username/works/project-name/r/node_modules/ecpay-aio-node/package.json' of 'ecpay_payment.js'. Please either fix that or report it to the module author
[0] (Use `node --trace-deprecation ...` to show where the warning was created)`

今天開啟 server , npm 跳出這警示。

**Comment by AllennChang** [comment]
您好, 請用我們官方上傳的套件,  [ecpay_aio_nodejs](https://www.npmjs.com/package/ecpay_aio_nodejs) , 若有問題歡迎再跟我們反應, 謝謝您的反應
