### ISSUE TITLE
npm install 並不會安裝到更新後的版本

### ISSUE THREAD

**Issue by EdwinKuo1337** [ECPay/ECPayAIO_Node.js#16]
您好，感謝您在快速的時間內就回應的我之前的Issues

不過我現在如果下`npm install ecpay_aio_nodejs`時還是會安裝到舊的版本，是否是因為沒有將新的版本publish至npm registry呢？我有先把node_modules裡的package刪除，也把package-lock.json刪除，再重新安裝，還是裝到舊版的（應該是比[這個commit](https://github.com/ECPay/ECPayAIO_Node.js/commit/b85a661d5754664671b5315cfc04d13cb8dbd693)還要舊，因為我看安裝下來package的`README.md`是這個commit以前的版本）

我看起來版本號還是跟之前的一樣，[在npm registry的package](https://www.npmjs.com/package/ecpay_aio_nodejs?activeTab=readme)也還是顯示舊的package，再請您看一下，謝謝

**Comment by AllennChang** [comment]
抱歉, 昨日只更新了github ,目前已經更新到npm 了, 請在重試安裝, 感謝

**Comment by EdwinKuo1337** [comment]
現在能正確安裝到1.2.2版本了，感謝！
