### ISSUE TITLE
電子發票參數名字問題

### ISSUE THREAD

**Issue by EdwinKuo1337** [ECPay/ECPayAIO_Node.js#17]
https://github.com/ECPay/ECPayAIO_Node.js/blob/0ad1802d0df33df59fa9122eac751404221c2206/ECPAY_Payment_node_js/example/aio_check_out_credit_period.js#L38-L39

您好，我發現在信用卡定期定額的範例當中的電子發票參數，其中`CarrierType`和`CarrierNum `與[官網中](https://developers.ecpay.com.tw/?p=7896)的拼法並不一樣，是否有打錯？還是說就照著code裡面的名字用就好了？

**Comment by AllennChang** [comment]
您好, 範例中的參數是舊規格電子發票的參數, 是正確的沒有錯,
官網中的為新規格的電子發票有調整過參數命名, 所以跟舊規格有差異, 
建議若是定期定額的交易,電子發票可以在收到付款通知時另外串接電子發票新規格自行呼叫, 
若還有任何問題,歡迎隨時再跟我們反應, 感謝您的詢問
