### ISSUE TITLE
Feature request: 回傳交易IP位置參數

### ISSUE THREAD

**Issue by EdwinKuo1337** [ECPay/ECPayAIO_Node.js#18]
您好，

我發現在綠界廠商後台->信用卡收單->交易明細查詢，當我點進一筆交易的授權單號數字後，可以看到交易詳細資料，其中包含該筆交易的IP位置（如圖所示）由於我們開發票需要用到交易的IP位置，所以需要自動化的話就會需要能夠自動地得到交易IP位置

但是我在全方位金流API文件中並沒有看到可以透過一筆交易的MerchantTradeNo（或是其他交易相關的參數）去query（不論是一次付清or定期定額的信用卡）交易的IP位置
我想請綠界工程師幫我在NodeJs sdk中增加這個feature: 藉由一筆交易的參數（不論是MerchantTradeNo或是授權單號等等的參數）去query，然後回傳這筆交易的IP位置（不限IP位置，也能包含其他交易詳細資訊，但需要包含IP位置），謝謝

<img width="1270" alt="Screenshot 2024-06-06 at 16 35 15" src="https://github.com/ECPay/ECPayAIO_Node.js/assets/67383544/9099e893-5e4e-4e8e-b029-b3c495914fb6">

**Comment by AllennChang** [comment]
您好,目前我們無法提供交易IP欄位, 若要使用NODE.JS取得客戶的IP 建議您可以參考網路上的相關文件, 例如https://stoner609.github.io/2018/12/19/20181219-node-getMachineName/
