### ISSUE TITLE
Publish on npm 

### ISSUE THREAD

**Issue by ckpiggy** [ECPay/ECPayAIO_Node.js#2]
Please consider to publish the module on npm/yarn, and accept a js object as option on create
ex: 
```
const options = {
    merchantID: ...,
    hashKey: ...,
    hashIV: ....
.....other option....
}
const create = new ecpay_payment(options)
.
.
.
```

**Comment by AllennChang** [comment]
感謝您的建議. 我會回報給我們開發團隊參考

**Comment by AllennChang** [comment]
您好, 我們目前的設定己都在設定檔中, 請參考 payment_conf.xml 檔, 感謝, 若有任何問題, 歡迎再次跟我們反應, 感謝您
