### ISSUE TITLE
文件內的捐贈發票參數標示錯誤

### ISSUE THREAD

**Issue by zackexplosion** [ECPay/ECPayAIO_Node.js#4]
文件內提到 aio_check_out_XXXX method 的發票參數中的 `donation` 可接受的值為 0 或 1
![image](https://user-images.githubusercontent.com/5180966/45918881-bf298380-bebf-11e8-83b4-31531facc988.png)

但實際上的程式碼只接受 `1` 或 `2`
![image](https://user-images.githubusercontent.com/5180966/45918873-af11a400-bebf-11e8-8169-98c7858d2ba6.png)

**Comment by AllennChang** [comment]
您好, 最新的文件件己更新, https://www.ecpay.com.tw/Content/files/ecpay_004.pdf , 若有任何問題, 歡迎再跟我們反應, 感謝您
