### ISSUE TITLE
付款結果通知

### ISSUE THREAD

**Issue by JackInTaiwan** [ECPay/ECPayAIO_Node.js#5]
請問關於付款結果通知（以信用卡一次付款為例），我們特店方的server會收到POST request，請問資訊會以json形式放在body給我們嗎？因為我在測試環境實測似乎是空的。

**Comment by AllennChang** [comment]
您好, 感謝你的發問, 目前綠界科技的付款結果通知會以下表 form-data 格式參數直接回傳至頁面，並以「參數=值」表示，參數與參數之間以&隔開 , 範例如下
&CustomField1=&CustomField2=&CustomField3=&CustomField4=&MerchantID=2000132
&MerchantTradeNo=Test1510056539&PaymentDate=2017/11/02 16:22:18
&PaymentType=Credit_CreditCard&PaymentTypeChargeFee=1&RtnCode=1&RtnMsg=交易成功
&SimulatePaid=0&StoreID=&TradeAmt=100&TradeDate=2017/11/07 20:08:59&TradeNo=1711072008596023
&CheckMacValue= DB6960E7B3765C2ACDDF8437B9D92EA14823B1B5BA11069017777D79A99A9F1E
