### ISSUE TITLE
不能包成 npm module 嗎 ?

### ISSUE THREAD

**Issue by karocksjoelee** [ECPay/ECPayAIO_Node.js#8]
`npm install ecpay `

??

**Comment by AllennChang** [comment]
您好, 感謝您的建議, 我們已完成上傳到npm ,請您再試試看用npm安裝 ,  感謝
若有任何問題, 歡迎再跟我們反應, 感謝您

**Comment by karocksjoelee** [comment]
請問一下 module 名字是?
建議將 npm install <MODULE> 名字與相關文件放置 README.MD 
這樣是 nodejs 開發者比較習慣的生態

**Comment by AllennChang** [comment]
已加上名稱, ecpay_aio_nodejs
